### ISSUE TITLE
Spin-off games?

### ISSUE THREAD

**Issue by Cruifer** [abcboy101/poke-corpus#2]
Is there any chances that spin-off games will be supported in the future? Would be much appreciated

**Comment by abcboy101** [comment]
As of writing, Stadium, Stadium 2, Box, Colosseum, XD, PBR, Ranch, Bank, HOME, GO, and Masters EX have been added. I think these are the most relevant titles for the purpose of comparing text between games.

I have text dumps for more spin-offs on my Bulbapedia [userpage](https://bulbapedia.bulbagarden.net/wiki/User:Abcboy#Text_dumps), but I currently don't have plans to process them into a format suitable for Poké Corpus myself.
