### ISSUE TITLE
Pre gen 4 support for other languages?

### ISSUE THREAD

**Issue by Cruifer** [abcboy101/poke-corpus#3]
The tool is showing other languages only for gen >= 4 games. For gen 1, 2 & 3 only english is showing. Will missing languages be added in the future?

**Comment by abcboy101** [comment]
The text dumps for these games in other languages can be searched by selecting the appropriate language filter. As these games do not have a file system like later games, there is no line-to-line correspondence between different languages, without someone manually organizing the text.
