### ISSUE TITLE
[Question] Text encoding for the `poke-corpus/corpus/*/*.txt` files

### ISSUE THREAD

**Issue by alvations** [abcboy101/poke-corpus#4]
Hi, thank you for sharing the compiling the data into this repo! 

I'll like to ask how would you figure out the text encoding for the different files in the `poke-corpus/corpus/*/*.txt` directories? I see that on the GUI, the https://abcboy101.github.io/poke-corpus/ the query results rendered into utf8 in my browser properly. But when I tried to open the raw *.txt files they don't seem to be in utf8.

Thank you in advance for the info!

**Comment by abcboy101** [comment]
The text encoding for all of the text dumps is indeed UTF-8. I'd guess that your text editor or browser is misinterpreting it as some other encoding. For the GB/GBC/GBA games, the text is mixed in with some junk data, but it's also in UTF-8.

**Comment by alvations** [comment]
Thanks for the quick reply! 

One more quick question, are the line numbers aligned across the languages? 

E.g. I saw that they are for this pair:

- https://github.com/abcboy101/poke-corpus/blob/main/corpus/BlackWhite/en-US_common.txt
- https://github.com/abcboy101/poke-corpus/blob/main/corpus/BlackWhite/de-DE_common.txt

**Comment by abcboy101** [comment]
Yes, all of them except for the ones for the GB/GBC/GBA are aligned by line number.
